import sys
from Node import Node
from LinkedList import LinkedList
from LinkedListIterator import LinkedListIterator

already_printed_error = False
points = 100
def test(expected, given, test_points):
    """ Print the result of a test. """
    global already_printed_error
    global points
    if already_printed_error == False:
        linenum = sys._getframe(1).f_lineno # Get the caller’s line number.
        if expected == given:
            msg = "Test at line {0} ok.".format(linenum)
            # print(msg)
        else:
            msg = ("\tTest at line {0} FAILED.".format(linenum))
            points -= test_points
            print(msg)
            print("\t\tExpected: "+ str(expected))
            print("\t\ttype: "+ str(type(expected)))
            print("\t\tGiven   : "+ str(given))
            print("\t\ttype: "+ str(type(given)))
            print("\t\tTester only prints a single error per section - there may be more")
            already_printed_error = True

def test_suite():
    """ Run the suite of tests for code in this module (this file).
    """
    global already_printed_error
    print("Starting tests - only failed tests print unless you change that")
    #Add your tests here

    #Dr B's tests follow:
    print('testing init with good values')
    already_printed_error = False
    list = LinkedList()
    list.add('Ontarian')
    list.add('Weierstrass')
    list.add('showcase')
    iter = LinkedListIterator(list)
    list = LinkedList()
    list.add('diminutive')
    list.add('larceny')
    iter = LinkedListIterator(list)
    list = LinkedList()
    list.add('despondence')
    list.add('interment')
    list.add('pontifical')
    iter = LinkedListIterator(list)
    print('testing init with bad values')
    try:
        iter = LinkedListIterator('pissoir')
        test(ValueError('ValueError'),'no error', 10)
    except AttributeError as err:
        test('no error', 'Attribute Error occured', 10)
    except ValueError as err:
        test(True,True, 10)
    try:
        iter = LinkedListIterator('Merlot')
        test(ValueError('ValueError'),'no error', 10)
    except AttributeError as err:
        test('no error', 'Attribute Error occured', 10)
    except ValueError as err:
        test(True,True, 10)
    try:
        iter = LinkedListIterator('photo')
        test(ValueError('ValueError'),'no error', 10)
    except AttributeError as err:
        test('no error', 'Attribute Error occured', 10)
    except ValueError as err:
        test(True,True, 10)
    try:
        iter = LinkedListIterator(213)
        test(ValueError('ValueError'),'no error', 10)
    except AttributeError as err:
        test('no error', 'Attribute Error occured', 10)
    except ValueError as err:
        test(True,True, 10)
    try:
        iter = LinkedListIterator(131)
        test(ValueError('ValueError'),'no error', 10)
    except AttributeError as err:
        test('no error', 'Attribute Error occured', 10)
    except ValueError as err:
        test(True,True, 10)
    try:
        iter = LinkedListIterator(976)
        test(ValueError('ValueError'),'no error', 10)
    except AttributeError as err:
        test('no error', 'Attribute Error occured', 10)
    except ValueError as err:
        test(True,True, 10)
    try:
        iter = LinkedListIterator(557.7891200247859)
        test(ValueError('ValueError'),'no error', 10)
    except AttributeError as err:
        test('no error', 'Attribute Error occured', 10)
    except ValueError as err:
        test(True,True, 10)
    try:
        iter = LinkedListIterator(1020.5973335195449)
        test(ValueError('ValueError'),'no error', 10)
    except AttributeError as err:
        test('no error', 'Attribute Error occured', 10)
    except ValueError as err:
        test(True,True, 10)
    try:
        iter = LinkedListIterator(645.6294072361993)
        test(ValueError('ValueError'),'no error', 10)
    except AttributeError as err:
        test('no error', 'Attribute Error occured', 10)
    except ValueError as err:
        test(True,True, 10)
    try:
        iter = LinkedListIterator(True)
        test(ValueError('ValueError'),'no error', 10)
    except AttributeError as err:
        test('no error', 'Attribute Error occured', 10)
    except ValueError as err:
        test(True,True, 10)
    try:
        iter = LinkedListIterator(False)
        test(ValueError('ValueError'),'no error', 10)
    except AttributeError as err:
        test('no error', 'Attribute Error occured', 10)
    except ValueError as err:
        test(True,True, 10)
    print('testing size_of_list')
    already_printed_error = False
    list = LinkedList()
    list.add('shortness')
    list.add('Judea')
    list.add('geophysical')
    list.add('Marius')
    list.add('Hegel')
    list.add('stevedore')
    list.add('boogieman')
    list.add('Whitney')
    list.add('waged')
    list.add('infinitival')
    list.add('chieftain')
    list.add('administration')
    list.add('hardworking')
    iter = LinkedListIterator(list)
    test(13, iter.size_of_list(), 10)
    list = LinkedList()
    list.add('Ceylon')
    list.add('desalination')
    list.add('sapsucker')
    list.add('gagged')
    iter = LinkedListIterator(list)
    test(4, iter.size_of_list(), 10)
    list = LinkedList()
    iter = LinkedListIterator(list)
    test(0, iter.size_of_list(), 10)
    list = LinkedList()
    list.add('KKK')
    list.add('Nansen')
    list.add('turnoff')
    list.add('mainstream')
    list.add('messianic')
    list.add('breaststroke')
    list.add('lazybones')
    list.add('upsetting')
    list.add('flameproof')
    iter = LinkedListIterator(list)
    test(9, iter.size_of_list(), 10)
    list = LinkedList()
    list.add('commode')
    list.add('rosewater')
    list.add('whistler')
    list.add('forefinger')
    list.add('Odom')
    list.add('umbilicus')
    list.add('socialite')
    list.add('polyphony')
    list.add('mutineer')
    list.add('hydrophone')
    list.add('stow')
    list.add('spectacle')
    list.add('theorize')
    list.add('capon')
    list.add('escalope')
    list.add('slowdown')
    list.add('Disneyland')
    list.add('laundrywomen')
    iter = LinkedListIterator(list)
    test(18, iter.size_of_list(), 10)
    list = LinkedList()
    list.add('Lilliputian')
    list.add('barge')
    list.add('trans')
    list.add('whyd')
    list.add('elbowroom')
    list.add('guinea')
    list.add('controller')
    list.add('vagueness')
    list.add('Saskatchewan')
    list.add('tracery')
    list.add('thunk')
    list.add('betake')
    list.add('rotation')
    list.add('demijohn')
    list.add('personality')
    list.add('Orbison')
    list.add('papery')
    iter = LinkedListIterator(list)
    test(17, iter.size_of_list(), 10)
    list = LinkedList()
    list.add('mind')
    list.add('Apalachicola')
    list.add('acclaim')
    list.add('ethnological')
    list.add('shamelessness')
    list.add('Galilean')
    list.add('thermodynamic')
    list.add('anise')
    list.add('McFadden')
    list.add('gloss')
    list.add('bitcoin')
    list.add('quadrilateral')
    list.add('creak')
    list.add('Wright')
    iter = LinkedListIterator(list)
    test(14, iter.size_of_list(), 10)
    list = LinkedList()
    list.add('coccyx')
    list.add('rakish')
    list.add('amphetamine')
    list.add('perniciousness')
    list.add('Magellan')
    list.add('avarice')
    list.add('Sedna')
    list.add('spinney')
    list.add('transplantation')
    list.add('prognosticate')
    list.add('laboratory')
    list.add('divestiture')
    list.add('Eloy')
    list.add('tinniness')
    list.add('gigging')
    iter = LinkedListIterator(list)
    test(15, iter.size_of_list(), 10)
    list = LinkedList()
    list.add('clod')
    list.add('Arlene')
    list.add('Swaziland')
    list.add('Flatt')
    list.add('sleepyhead')
    iter = LinkedListIterator(list)
    test(5, iter.size_of_list(), 10)
    list = LinkedList()
    list.add('gripper')
    list.add('muskrat')
    list.add('Stern')
    list.add('bedsore')
    list.add('demagoguery')
    list.add('budded')
    list.add('hairspring')
    list.add('towel')
    list.add('tailwind')
    list.add('death')
    iter = LinkedListIterator(list)
    test(10, iter.size_of_list(), 10)
    print('testing get_beginning_node on a list with no nodes')
    already_printed_error = False
    list = LinkedList()
    iter = LinkedListIterator(list)
    test(None, iter.get_beginning_node(), 5)
    print('testing get_beginning_node on a list with several nodes')
    already_printed_error = False
    list = LinkedList()
    list.add('Melisande')
    iter = LinkedListIterator(list)
    tmpNode = Node('Melisande')
    test(tmpNode, iter.get_beginning_node(), 5)
    list = LinkedList()
    list.add('sir')
    list.add('floor')
    list.add('Homer')
    list.add('sepsis')
    list.add('classicist')
    iter = LinkedListIterator(list)
    tmpNode = Node('classicist')
    test(tmpNode, iter.get_beginning_node(), 5)
    list = LinkedList()
    list.add('arachnid')
    list.add('liberate')
    list.add('fasten')
    iter = LinkedListIterator(list)
    tmpNode = Node('fasten')
    test(tmpNode, iter.get_beginning_node(), 5)
    list = LinkedList()
    list.add('Alison')
    list.add('nucleic')
    list.add('scag')
    list.add('godless')
    list.add('prefabbed')
    list.add('tipper')
    list.add('sonsofbitches')
    list.add('Baggies')
    iter = LinkedListIterator(list)
    tmpNode = Node('Baggies')
    test(tmpNode, iter.get_beginning_node(), 5)
    list = LinkedList()
    list.add('Bridgetown')
    list.add('broaden')
    list.add('chef')
    list.add('Cabrini')
    list.add('promulgation')
    list.add('Jericho')
    iter = LinkedListIterator(list)
    tmpNode = Node('Jericho')
    test(tmpNode, iter.get_beginning_node(), 5)
    list = LinkedList()
    list.add('var')
    list.add('childishness')
    list.add('Dawson')
    list.add('eBay')
    iter = LinkedListIterator(list)
    tmpNode = Node('eBay')
    test(tmpNode, iter.get_beginning_node(), 5)
    list = LinkedList()
    list.add('leguminous')
    list.add('shark')
    list.add('gargle')
    list.add('Calvert')
    list.add('ambidextrous')
    list.add('Philby')
    list.add('workweek')
    iter = LinkedListIterator(list)
    tmpNode = Node('workweek')
    test(tmpNode, iter.get_beginning_node(), 5)
    list = LinkedList()
    list.add('Gascony')
    list.add('serum')
    iter = LinkedListIterator(list)
    tmpNode = Node('serum')
    test(tmpNode, iter.get_beginning_node(), 5)
    list = LinkedList()
    list.add('acquaintance')
    list.add('Kislev')
    list.add('nacho')
    list.add('damson')
    list.add('titanic')
    list.add('Maputo')
    list.add('Linotype')
    list.add('monkish')
    list.add('DiMaggio')
    iter = LinkedListIterator(list)
    tmpNode = Node('DiMaggio')
    test(tmpNode, iter.get_beginning_node(), 5)
    print('testing get_ending_node on a list with no nodes')
    already_printed_error = False
    list = LinkedList()
    iter = LinkedListIterator(list)
    test(None, iter.get_ending_node(), 5)
    print('testing get_ending_node on a list with several nodes')
    already_printed_error = False
    list = LinkedList()
    list.add('DNA')
    iter = LinkedListIterator(list)
    tmpNode = Node('DNA')
    test(tmpNode, iter.get_ending_node(), 5)
    list = LinkedList()
    list.add('abdicate')
    list.add('men')
    list.add('gas')
    list.add('cortical')
    list.add('subprogram')
    list.add('entrancing')
    list.add('Navajo')
    list.add('Brittany')
    iter = LinkedListIterator(list)
    tmpNode = Node('abdicate')
    test(tmpNode, iter.get_ending_node(), 5)
    list = LinkedList()
    list.add('color')
    list.add('racketeer')
    list.add('Bloomingdale')
    list.add('particleboard')
    list.add('crunchy')
    list.add('federalist')
    iter = LinkedListIterator(list)
    tmpNode = Node('color')
    test(tmpNode, iter.get_ending_node(), 5)
    list = LinkedList()
    list.add('wildflower')
    list.add('Sacco')
    list.add('twerp')
    list.add('Puck')
    iter = LinkedListIterator(list)
    tmpNode = Node('wildflower')
    test(tmpNode, iter.get_ending_node(), 5)
    list = LinkedList()
    list.add('grandmother')
    list.add('privy')
    list.add('rid')
    list.add('lipstick')
    list.add('albino')
    list.add('Themistocles')
    list.add('rusticity')
    iter = LinkedListIterator(list)
    tmpNode = Node('grandmother')
    test(tmpNode, iter.get_ending_node(), 5)
    list = LinkedList()
    list.add('congestion')
    list.add('adventitious')
    list.add('finger')
    iter = LinkedListIterator(list)
    tmpNode = Node('congestion')
    test(tmpNode, iter.get_ending_node(), 5)
    list = LinkedList()
    list.add('obese')
    list.add('Schwinger')
    list.add('Bradly')
    list.add('fuel')
    list.add('belch')
    list.add('saltbox')
    list.add('discharged')
    list.add('Gatsby')
    list.add('campaigner')
    iter = LinkedListIterator(list)
    tmpNode = Node('obese')
    test(tmpNode, iter.get_ending_node(), 5)
    list = LinkedList()
    list.add('lopped')
    list.add('outre')
    iter = LinkedListIterator(list)
    tmpNode = Node('lopped')
    test(tmpNode, iter.get_ending_node(), 5)
    list = LinkedList()
    list.add('scullery')
    list.add('hallowed')
    list.add('gimcrack')
    list.add('Irishwomen')
    list.add('fluorescence')
    iter = LinkedListIterator(list)
    tmpNode = Node('scullery')
    test(tmpNode, iter.get_ending_node(), 5)
    print('testing advance_to_next_node on a list with no nodes')
    already_printed_error = False
    list = LinkedList()
    iter = LinkedListIterator(list)
    try:
        test(None,iter.get_node_at_current_location(), 5)
    except AttributeError as err:
        test('no error', 'Attribute Error occured', 5)
    except ValueError as err:
        test('no error', 'Value Error occured', 5)
    print('testing advance_to_next_node on a list with several nodes')
    already_printed_error = False
    list = LinkedList()
    list.add('borrowing')
    list.add('Recife')
    list.add('een')
    list.add('fatalist')
    iter = LinkedListIterator(list)
    test(Node('fatalist'), iter.get_node_at_current_location(), 5)
    iter.advance_to_next_node()
    test(Node('een'), iter.get_node_at_current_location(), 5)
    iter.advance_to_next_node()
    test(Node('Recife'), iter.get_node_at_current_location(), 5)
    iter.advance_to_next_node()
    test(Node('borrowing'), iter.get_node_at_current_location(), 5)
    list = LinkedList()
    list.add('generation')
    list.add('uncomplaining')
    list.add('sleuths')
    list.add('typical')
    list.add('Randolph')
    list.add('grimness')
    iter = LinkedListIterator(list)
    test(Node('grimness'), iter.get_node_at_current_location(), 5)
    iter.advance_to_next_node()
    test(Node('Randolph'), iter.get_node_at_current_location(), 5)
    iter.advance_to_next_node()
    test(Node('typical'), iter.get_node_at_current_location(), 5)
    iter.advance_to_next_node()
    test(Node('sleuths'), iter.get_node_at_current_location(), 5)
    iter.advance_to_next_node()
    test(Node('uncomplaining'), iter.get_node_at_current_location(), 5)
    iter.advance_to_next_node()
    test(Node('generation'), iter.get_node_at_current_location(), 5)
    list = LinkedList()
    list.add('perceptibly')
    list.add('ripeness')
    list.add('optimum')
    list.add('scraggy')
    list.add('amigo')
    iter = LinkedListIterator(list)
    test(Node('amigo'), iter.get_node_at_current_location(), 5)
    iter.advance_to_next_node()
    test(Node('scraggy'), iter.get_node_at_current_location(), 5)
    iter.advance_to_next_node()
    test(Node('optimum'), iter.get_node_at_current_location(), 5)
    iter.advance_to_next_node()
    test(Node('ripeness'), iter.get_node_at_current_location(), 5)
    iter.advance_to_next_node()
    test(Node('perceptibly'), iter.get_node_at_current_location(), 5)
    list = LinkedList()
    list.add('snoop')
    iter = LinkedListIterator(list)
    test(Node('snoop'), iter.get_node_at_current_location(), 5)
    list = LinkedList()
    list.add('occlusive')
    list.add('primogenitor')
    list.add('Timur')
    list.add('bleach')
    list.add('Pullman')
    list.add('tarmacked')
    list.add('overbid')
    list.add('Salyut')
    list.add('croaky')
    iter = LinkedListIterator(list)
    test(Node('croaky'), iter.get_node_at_current_location(), 5)
    iter.advance_to_next_node()
    test(Node('Salyut'), iter.get_node_at_current_location(), 5)
    iter.advance_to_next_node()
    test(Node('overbid'), iter.get_node_at_current_location(), 5)
    iter.advance_to_next_node()
    test(Node('tarmacked'), iter.get_node_at_current_location(), 5)
    iter.advance_to_next_node()
    test(Node('Pullman'), iter.get_node_at_current_location(), 5)
    iter.advance_to_next_node()
    test(Node('bleach'), iter.get_node_at_current_location(), 5)
    iter.advance_to_next_node()
    test(Node('Timur'), iter.get_node_at_current_location(), 5)
    iter.advance_to_next_node()
    test(Node('primogenitor'), iter.get_node_at_current_location(), 5)
    iter.advance_to_next_node()
    test(Node('occlusive'), iter.get_node_at_current_location(), 5)
    list = LinkedList()
    list.add('Nehemiah')
    list.add('plop')
    iter = LinkedListIterator(list)
    test(Node('plop'), iter.get_node_at_current_location(), 5)
    iter.advance_to_next_node()
    test(Node('Nehemiah'), iter.get_node_at_current_location(), 5)
    list = LinkedList()
    list.add('leashs')
    list.add('stateroom')
    list.add('Bowditch')
    list.add('Selassie')
    list.add('streaky')
    list.add('damper')
    list.add('cloche')
    list.add('Marcuse')
    iter = LinkedListIterator(list)
    test(Node('Marcuse'), iter.get_node_at_current_location(), 5)
    iter.advance_to_next_node()
    test(Node('cloche'), iter.get_node_at_current_location(), 5)
    iter.advance_to_next_node()
    test(Node('damper'), iter.get_node_at_current_location(), 5)
    iter.advance_to_next_node()
    test(Node('streaky'), iter.get_node_at_current_location(), 5)
    iter.advance_to_next_node()
    test(Node('Selassie'), iter.get_node_at_current_location(), 5)
    iter.advance_to_next_node()
    test(Node('Bowditch'), iter.get_node_at_current_location(), 5)
    iter.advance_to_next_node()
    test(Node('stateroom'), iter.get_node_at_current_location(), 5)
    iter.advance_to_next_node()
    test(Node('leashs'), iter.get_node_at_current_location(), 5)
    list = LinkedList()
    list.add('Lome')
    list.add('Grover')
    list.add('Maalox')
    iter = LinkedListIterator(list)
    test(Node('Maalox'), iter.get_node_at_current_location(), 5)
    iter.advance_to_next_node()
    test(Node('Grover'), iter.get_node_at_current_location(), 5)
    iter.advance_to_next_node()
    test(Node('Lome'), iter.get_node_at_current_location(), 5)
    list = LinkedList()
    list.add('alkali')
    list.add('formulation')
    list.add('hackitude')
    list.add('noncombat')
    list.add('incise')
    list.add('nontoxic')
    list.add('turn')
    iter = LinkedListIterator(list)
    test(Node('turn'), iter.get_node_at_current_location(), 5)
    iter.advance_to_next_node()
    test(Node('nontoxic'), iter.get_node_at_current_location(), 5)
    iter.advance_to_next_node()
    test(Node('incise'), iter.get_node_at_current_location(), 5)
    iter.advance_to_next_node()
    test(Node('noncombat'), iter.get_node_at_current_location(), 5)
    iter.advance_to_next_node()
    test(Node('hackitude'), iter.get_node_at_current_location(), 5)
    iter.advance_to_next_node()
    test(Node('formulation'), iter.get_node_at_current_location(), 5)
    iter.advance_to_next_node()
    test(Node('alkali'), iter.get_node_at_current_location(), 5)
    print('testing advance_to_next_node on a list with several nodes, for all nodes in list')
    already_printed_error = False
    list = LinkedList()
    list.add('lifebelt')
    list.add('gabbiness')
    list.add('Clayton')
    list.add('tailback')
    list.add('befog')
    list.add('tablecloth')
    list.add('housebroken')
    list.add('sylphlike')
    iter = LinkedListIterator(list)
    iter.advance_to_next_node()
    iter.advance_to_next_node()
    iter.advance_to_next_node()
    iter.advance_to_next_node()
    iter.advance_to_next_node()
    iter.advance_to_next_node()
    iter.advance_to_next_node()
    try:
        iter.advance_to_next_node()
        test('IndexError', 'no error occured', 5)
    except IndexError as err:
        test('IndexError', 'IndexError', 5)
    except AttributeError as err:
        test('IndexError', 'Attribute Error occured', 5)
    except ValueError as err:
        test('IndexError', 'ValueError', 5)
    list = LinkedList()
    list.add('Athabasca')
    list.add('lecher')
    list.add('gaslight')
    iter = LinkedListIterator(list)
    iter.advance_to_next_node()
    iter.advance_to_next_node()
    try:
        iter.advance_to_next_node()
        test('IndexError', 'no error occured', 5)
    except IndexError as err:
        test('IndexError', 'IndexError', 5)
    except AttributeError as err:
        test('IndexError', 'Attribute Error occured', 5)
    except ValueError as err:
        test('IndexError', 'ValueError', 5)
    list = LinkedList()
    list.add('psychos')
    list.add('amphorae')
    list.add('buckram')
    list.add('pro')
    iter = LinkedListIterator(list)
    iter.advance_to_next_node()
    iter.advance_to_next_node()
    iter.advance_to_next_node()
    try:
        iter.advance_to_next_node()
        test('IndexError', 'no error occured', 5)
    except IndexError as err:
        test('IndexError', 'IndexError', 5)
    except AttributeError as err:
        test('IndexError', 'Attribute Error occured', 5)
    except ValueError as err:
        test('IndexError', 'ValueError', 5)
    list = LinkedList()
    list.add('parsimonious')
    list.add('babushka')
    list.add('Selim')
    list.add('overtaken')
    list.add('churlishness')
    list.add('rakishness')
    iter = LinkedListIterator(list)
    iter.advance_to_next_node()
    iter.advance_to_next_node()
    iter.advance_to_next_node()
    iter.advance_to_next_node()
    iter.advance_to_next_node()
    try:
        iter.advance_to_next_node()
        test('IndexError', 'no error occured', 5)
    except IndexError as err:
        test('IndexError', 'IndexError', 5)
    except AttributeError as err:
        test('IndexError', 'Attribute Error occured', 5)
    except ValueError as err:
        test('IndexError', 'ValueError', 5)
    list = LinkedList()
    list.add('viii')
    list.add('MC')
    iter = LinkedListIterator(list)
    iter.advance_to_next_node()
    try:
        iter.advance_to_next_node()
        test('IndexError', 'no error occured', 5)
    except IndexError as err:
        test('IndexError', 'IndexError', 5)
    except AttributeError as err:
        test('IndexError', 'Attribute Error occured', 5)
    except ValueError as err:
        test('IndexError', 'ValueError', 5)
    list = LinkedList()
    list.add('Google')
    list.add('alternator')
    list.add('mandolin')
    list.add('molluscan')
    list.add('mine')
    list.add('competitor')
    list.add('despondent')
    list.add('punchline')
    list.add('prevaricator')
    iter = LinkedListIterator(list)
    iter.advance_to_next_node()
    iter.advance_to_next_node()
    iter.advance_to_next_node()
    iter.advance_to_next_node()
    iter.advance_to_next_node()
    iter.advance_to_next_node()
    iter.advance_to_next_node()
    iter.advance_to_next_node()
    try:
        iter.advance_to_next_node()
        test('IndexError', 'no error occured', 5)
    except IndexError as err:
        test('IndexError', 'IndexError', 5)
    except AttributeError as err:
        test('IndexError', 'Attribute Error occured', 5)
    except ValueError as err:
        test('IndexError', 'ValueError', 5)
    list = LinkedList()
    list.add('catboat')
    iter = LinkedListIterator(list)
    try:
        iter.advance_to_next_node()
        test('IndexError', 'no error occured', 5)
    except IndexError as err:
        test('IndexError', 'IndexError', 5)
    except AttributeError as err:
        test('IndexError', 'Attribute Error occured', 5)
    except ValueError as err:
        test('IndexError', 'ValueError', 5)
    list = LinkedList()
    list.add('combustible')
    list.add('Steven')
    list.add('stereoscope')
    list.add('moneybag')
    list.add('exploration')
    iter = LinkedListIterator(list)
    iter.advance_to_next_node()
    iter.advance_to_next_node()
    iter.advance_to_next_node()
    iter.advance_to_next_node()
    try:
        iter.advance_to_next_node()
        test('IndexError', 'no error occured', 5)
    except IndexError as err:
        test('IndexError', 'IndexError', 5)
    except AttributeError as err:
        test('IndexError', 'Attribute Error occured', 5)
    except ValueError as err:
        test('IndexError', 'ValueError', 5)
    list = LinkedList()
    list.add('unidirectional')
    list.add('famish')
    list.add('Sankara')
    list.add('essence')
    list.add('autoimmune')
    list.add('transnational')
    list.add('climb')
    iter = LinkedListIterator(list)
    iter.advance_to_next_node()
    iter.advance_to_next_node()
    iter.advance_to_next_node()
    iter.advance_to_next_node()
    iter.advance_to_next_node()
    iter.advance_to_next_node()
    try:
        iter.advance_to_next_node()
        test('IndexError', 'no error occured', 5)
    except IndexError as err:
        test('IndexError', 'IndexError', 5)
    except AttributeError as err:
        test('IndexError', 'Attribute Error occured', 5)
    except ValueError as err:
        test('IndexError', 'ValueError', 5)
    print('testing has_next_node on a list with no nodes')
    already_printed_error = False
    list = LinkedList()
    iter = LinkedListIterator(list)
    try:
        test(False, iter.has_next_node(), 15)
    except AttributeError as err:
        test('no error', 'Attribute Error occured ' + str(err), 5)
    except ValueError as err:
        test('no error', 'Value Error occured ' + str(err), 5)
    print('testing has_next_node on a list with several nodes, for all nodes in list')
    already_printed_error = False
    list = LinkedList()
    list.add('gun')
    list.add('bezel')
    list.add('Salisbury')
    list.add('tinge')
    list.add('compartmentalization')
    list.add('treetop')
    list.add('harvested')
    list.add('viewpoint')
    list.add('judicial')
    iter = LinkedListIterator(list)
    test(True, iter.has_next_node(), 10)
    iter.advance_to_next_node()
    test(True, iter.has_next_node(), 10)
    iter.advance_to_next_node()
    test(True, iter.has_next_node(), 10)
    iter.advance_to_next_node()
    test(True, iter.has_next_node(), 10)
    iter.advance_to_next_node()
    test(True, iter.has_next_node(), 10)
    iter.advance_to_next_node()
    test(True, iter.has_next_node(), 10)
    iter.advance_to_next_node()
    test(True, iter.has_next_node(), 10)
    iter.advance_to_next_node()
    test(True, iter.has_next_node(), 10)
    iter.advance_to_next_node()
    try:
        test(False, iter.has_next_node(), 10)
    except AttributeError as err:
        test('no error', 'Attribute Error occured', 10)
    except ValueError as err:
        test('no error', 'Value Error occured', 10)
    except IndexError as err:
        test('no error', 'IndexError', 10)
    list = LinkedList()
    list.add('vulpine')
    list.add('reciprocation')
    list.add('tome')
    list.add('deliriousness')
    list.add('Galileo')
    list.add('decapitator')
    list.add('woodworker')
    iter = LinkedListIterator(list)
    test(True, iter.has_next_node(), 10)
    iter.advance_to_next_node()
    test(True, iter.has_next_node(), 10)
    iter.advance_to_next_node()
    test(True, iter.has_next_node(), 10)
    iter.advance_to_next_node()
    test(True, iter.has_next_node(), 10)
    iter.advance_to_next_node()
    test(True, iter.has_next_node(), 10)
    iter.advance_to_next_node()
    test(True, iter.has_next_node(), 10)
    iter.advance_to_next_node()
    try:
        test(False, iter.has_next_node(), 10)
    except AttributeError as err:
        test('no error', 'Attribute Error occured', 10)
    except ValueError as err:
        test('no error', 'Value Error occured', 10)
    except IndexError as err:
        test('no error', 'IndexError', 10)
    list = LinkedList()
    list.add('pastrami')
    list.add('Apocrypha')
    list.add('lox')
    iter = LinkedListIterator(list)
    test(True, iter.has_next_node(), 10)
    iter.advance_to_next_node()
    test(True, iter.has_next_node(), 10)
    iter.advance_to_next_node()
    try:
        test(False, iter.has_next_node(), 10)
    except AttributeError as err:
        test('no error', 'Attribute Error occured', 10)
    except ValueError as err:
        test('no error', 'Value Error occured', 10)
    except IndexError as err:
        test('no error', 'IndexError', 10)
    list = LinkedList()
    list.add('tangibility')
    list.add('Yellowstone')
    list.add('Ramsey')
    list.add('rescind')
    list.add('noes')
    list.add('misspoke')
    list.add('generational')
    list.add('gunner')
    iter = LinkedListIterator(list)
    test(True, iter.has_next_node(), 10)
    iter.advance_to_next_node()
    test(True, iter.has_next_node(), 10)
    iter.advance_to_next_node()
    test(True, iter.has_next_node(), 10)
    iter.advance_to_next_node()
    test(True, iter.has_next_node(), 10)
    iter.advance_to_next_node()
    test(True, iter.has_next_node(), 10)
    iter.advance_to_next_node()
    test(True, iter.has_next_node(), 10)
    iter.advance_to_next_node()
    test(True, iter.has_next_node(), 10)
    iter.advance_to_next_node()
    try:
        test(False, iter.has_next_node(), 10)
    except AttributeError as err:
        test('no error', 'Attribute Error occured', 10)
    except ValueError as err:
        test('no error', 'Value Error occured', 10)
    except IndexError as err:
        test('no error', 'IndexError', 10)
    list = LinkedList()
    list.add('Detroit')
    list.add('Bologna')
    list.add('wrinkly')
    list.add('accept')
    iter = LinkedListIterator(list)
    test(True, iter.has_next_node(), 10)
    iter.advance_to_next_node()
    test(True, iter.has_next_node(), 10)
    iter.advance_to_next_node()
    test(True, iter.has_next_node(), 10)
    iter.advance_to_next_node()
    try:
        test(False, iter.has_next_node(), 10)
    except AttributeError as err:
        test('no error', 'Attribute Error occured', 10)
    except ValueError as err:
        test('no error', 'Value Error occured', 10)
    except IndexError as err:
        test('no error', 'IndexError', 10)
    list = LinkedList()
    list.add('engrossment')
    list.add('nontheatrical')
    list.add('inherit')
    list.add('southwester')
    list.add('momentous')
    list.add('nodular')
    iter = LinkedListIterator(list)
    test(True, iter.has_next_node(), 10)
    iter.advance_to_next_node()
    test(True, iter.has_next_node(), 10)
    iter.advance_to_next_node()
    test(True, iter.has_next_node(), 10)
    iter.advance_to_next_node()
    test(True, iter.has_next_node(), 10)
    iter.advance_to_next_node()
    test(True, iter.has_next_node(), 10)
    iter.advance_to_next_node()
    try:
        test(False, iter.has_next_node(), 10)
    except AttributeError as err:
        test('no error', 'Attribute Error occured', 10)
    except ValueError as err:
        test('no error', 'Value Error occured', 10)
    except IndexError as err:
        test('no error', 'IndexError', 10)
    list = LinkedList()
    list.add('braid')
    list.add('waitress')
    iter = LinkedListIterator(list)
    test(True, iter.has_next_node(), 10)
    iter.advance_to_next_node()
    try:
        test(False, iter.has_next_node(), 10)
    except AttributeError as err:
        test('no error', 'Attribute Error occured', 10)
    except ValueError as err:
        test('no error', 'Value Error occured', 10)
    except IndexError as err:
        test('no error', 'IndexError', 10)
    list = LinkedList()
    list.add('Zzz')
    iter = LinkedListIterator(list)
    try:
        test(False, iter.has_next_node(), 10)
    except AttributeError as err:
        test('no error', 'Attribute Error occured', 10)
    except ValueError as err:
        test('no error', 'Value Error occured', 10)
    except IndexError as err:
        test('no error', 'IndexError', 10)
    list = LinkedList()
    list.add('hosier')
    list.add('boustrophedon')
    list.add('Elisabeth')
    list.add('Mazarin')
    list.add('timeliness')
    iter = LinkedListIterator(list)
    test(True, iter.has_next_node(), 10)
    iter.advance_to_next_node()
    test(True, iter.has_next_node(), 10)
    iter.advance_to_next_node()
    test(True, iter.has_next_node(), 10)
    iter.advance_to_next_node()
    test(True, iter.has_next_node(), 10)
    iter.advance_to_next_node()
    try:
        test(False, iter.has_next_node(), 10)
    except AttributeError as err:
        test('no error', 'Attribute Error occured', 10)
    except ValueError as err:
        test('no error', 'Value Error occured', 10)
    except IndexError as err:
        test('no error', 'IndexError', 10)
    print('testing go_back_a_node on a list with no nodes')
    already_printed_error = False
    list = LinkedList()
    iter = LinkedListIterator(list)
    try:
        iter.go_back_a_node()
        test('IndexError',iter.get_node_at_current_location(), 5)
    except AttributeError as err:
        test('no error', 'Attribute Error occured', 5)
    except ValueError as err:
        test('no error', 'Value Error occured', 5)
    except IndexError as err:
        test('IndexError', 'IndexError', 5)
    print('testing go_back_a_node on a list with no several nodes, for all nodes in list')
    already_printed_error = False
    list = LinkedList()
    list.add('fleabag')
    list.add('notifiable')
    list.add('impassibility')
    list.add('bigheartedness')
    list.add('harness')
    list.add('misalliance')
    iter = LinkedListIterator(list)
    iter.advance_to_next_node()
    iter.advance_to_next_node()
    iter.advance_to_next_node()
    iter.advance_to_next_node()
    iter.advance_to_next_node()
    test(Node('fleabag'), iter.get_node_at_current_location(), 10)
    iter.go_back_a_node()
    test(Node('notifiable'), iter.get_node_at_current_location(), 10)
    iter.go_back_a_node()
    test(Node('impassibility'), iter.get_node_at_current_location(), 10)
    iter.go_back_a_node()
    test(Node('bigheartedness'), iter.get_node_at_current_location(), 10)
    iter.go_back_a_node()
    test(Node('harness'), iter.get_node_at_current_location(), 10)
    iter.go_back_a_node()
    test(Node('misalliance'), iter.get_node_at_current_location(), 10)
    try:
        iter.go_back_a_node()
        test('IndexError', 'no error occured', 10)
    except IndexError as err:
        test('IndexError', 'IndexError', 10)
    except AttributeError as err:
        test('IndexError', 'Attribute Error occured', 10)
    except ValueError as err:
        test('IndexError', 'ValueError', 10)
    list = LinkedList()
    list.add('arty')
    list.add('Hipparchus')
    list.add('overmuch')
    list.add('gridiron')
    list.add('spanned')
    iter = LinkedListIterator(list)
    iter.advance_to_next_node()
    iter.advance_to_next_node()
    iter.advance_to_next_node()
    iter.advance_to_next_node()
    test(Node('arty'), iter.get_node_at_current_location(), 10)
    iter.go_back_a_node()
    test(Node('Hipparchus'), iter.get_node_at_current_location(), 10)
    iter.go_back_a_node()
    test(Node('overmuch'), iter.get_node_at_current_location(), 10)
    iter.go_back_a_node()
    test(Node('gridiron'), iter.get_node_at_current_location(), 10)
    iter.go_back_a_node()
    test(Node('spanned'), iter.get_node_at_current_location(), 10)
    try:
        iter.go_back_a_node()
        test('IndexError', 'no error occured', 10)
    except IndexError as err:
        test('IndexError', 'IndexError', 10)
    except AttributeError as err:
        test('IndexError', 'Attribute Error occured', 10)
    except ValueError as err:
        test('IndexError', 'ValueError', 10)
    list = LinkedList()
    list.add('activity')
    list.add('cucumber')
    list.add('oldish')
    list.add('arsonist')
    list.add('overstrung')
    list.add('petitioner')
    list.add('Parkinson')
    iter = LinkedListIterator(list)
    iter.advance_to_next_node()
    iter.advance_to_next_node()
    iter.advance_to_next_node()
    iter.advance_to_next_node()
    iter.advance_to_next_node()
    iter.advance_to_next_node()
    test(Node('activity'), iter.get_node_at_current_location(), 10)
    iter.go_back_a_node()
    test(Node('cucumber'), iter.get_node_at_current_location(), 10)
    iter.go_back_a_node()
    test(Node('oldish'), iter.get_node_at_current_location(), 10)
    iter.go_back_a_node()
    test(Node('arsonist'), iter.get_node_at_current_location(), 10)
    iter.go_back_a_node()
    test(Node('overstrung'), iter.get_node_at_current_location(), 10)
    iter.go_back_a_node()
    test(Node('petitioner'), iter.get_node_at_current_location(), 10)
    iter.go_back_a_node()
    test(Node('Parkinson'), iter.get_node_at_current_location(), 10)
    try:
        iter.go_back_a_node()
        test('IndexError', 'no error occured', 10)
    except IndexError as err:
        test('IndexError', 'IndexError', 10)
    except AttributeError as err:
        test('IndexError', 'Attribute Error occured', 10)
    except ValueError as err:
        test('IndexError', 'ValueError', 10)
    list = LinkedList()
    list.add('luminescent')
    list.add('genie')
    list.add('spoliation')
    iter = LinkedListIterator(list)
    iter.advance_to_next_node()
    iter.advance_to_next_node()
    test(Node('luminescent'), iter.get_node_at_current_location(), 10)
    iter.go_back_a_node()
    test(Node('genie'), iter.get_node_at_current_location(), 10)
    iter.go_back_a_node()
    test(Node('spoliation'), iter.get_node_at_current_location(), 10)
    try:
        iter.go_back_a_node()
        test('IndexError', 'no error occured', 10)
    except IndexError as err:
        test('IndexError', 'IndexError', 10)
    except AttributeError as err:
        test('IndexError', 'Attribute Error occured', 10)
    except ValueError as err:
        test('IndexError', 'ValueError', 10)
    list = LinkedList()
    list.add('taunting')
    list.add('tire')
    iter = LinkedListIterator(list)
    iter.advance_to_next_node()
    test(Node('taunting'), iter.get_node_at_current_location(), 10)
    iter.go_back_a_node()
    test(Node('tire'), iter.get_node_at_current_location(), 10)
    try:
        iter.go_back_a_node()
        test('IndexError', 'no error occured', 10)
    except IndexError as err:
        test('IndexError', 'IndexError', 10)
    except AttributeError as err:
        test('IndexError', 'Attribute Error occured', 10)
    except ValueError as err:
        test('IndexError', 'ValueError', 10)
    list = LinkedList()
    list.add('blotting')
    list.add('flak')
    list.add('dentistry')
    list.add('eisteddfod')
    iter = LinkedListIterator(list)
    iter.advance_to_next_node()
    iter.advance_to_next_node()
    iter.advance_to_next_node()
    test(Node('blotting'), iter.get_node_at_current_location(), 10)
    iter.go_back_a_node()
    test(Node('flak'), iter.get_node_at_current_location(), 10)
    iter.go_back_a_node()
    test(Node('dentistry'), iter.get_node_at_current_location(), 10)
    iter.go_back_a_node()
    test(Node('eisteddfod'), iter.get_node_at_current_location(), 10)
    try:
        iter.go_back_a_node()
        test('IndexError', 'no error occured', 10)
    except IndexError as err:
        test('IndexError', 'IndexError', 10)
    except AttributeError as err:
        test('IndexError', 'Attribute Error occured', 10)
    except ValueError as err:
        test('IndexError', 'ValueError', 10)
    list = LinkedList()
    list.add('modifier')
    list.add('summarily')
    list.add('Mazama')
    list.add('crane')
    list.add('Jesse')
    list.add('Nashville')
    list.add('clamminess')
    list.add('denotative')
    list.add('multiprocessor')
    iter = LinkedListIterator(list)
    iter.advance_to_next_node()
    iter.advance_to_next_node()
    iter.advance_to_next_node()
    iter.advance_to_next_node()
    iter.advance_to_next_node()
    iter.advance_to_next_node()
    iter.advance_to_next_node()
    iter.advance_to_next_node()
    test(Node('modifier'), iter.get_node_at_current_location(), 10)
    iter.go_back_a_node()
    test(Node('summarily'), iter.get_node_at_current_location(), 10)
    iter.go_back_a_node()
    test(Node('Mazama'), iter.get_node_at_current_location(), 10)
    iter.go_back_a_node()
    test(Node('crane'), iter.get_node_at_current_location(), 10)
    iter.go_back_a_node()
    test(Node('Jesse'), iter.get_node_at_current_location(), 10)
    iter.go_back_a_node()
    test(Node('Nashville'), iter.get_node_at_current_location(), 10)
    iter.go_back_a_node()
    test(Node('clamminess'), iter.get_node_at_current_location(), 10)
    iter.go_back_a_node()
    test(Node('denotative'), iter.get_node_at_current_location(), 10)
    iter.go_back_a_node()
    test(Node('multiprocessor'), iter.get_node_at_current_location(), 10)
    try:
        iter.go_back_a_node()
        test('IndexError', 'no error occured', 10)
    except IndexError as err:
        test('IndexError', 'IndexError', 10)
    except AttributeError as err:
        test('IndexError', 'Attribute Error occured', 10)
    except ValueError as err:
        test('IndexError', 'ValueError', 10)
    list = LinkedList()
    list.add('scallop')
    list.add('Booker')
    list.add('Castor')
    list.add('Huntington')
    list.add('winterize')
    list.add('complainant')
    list.add('XS')
    list.add('foggy')
    iter = LinkedListIterator(list)
    iter.advance_to_next_node()
    iter.advance_to_next_node()
    iter.advance_to_next_node()
    iter.advance_to_next_node()
    iter.advance_to_next_node()
    iter.advance_to_next_node()
    iter.advance_to_next_node()
    test(Node('scallop'), iter.get_node_at_current_location(), 10)
    iter.go_back_a_node()
    test(Node('Booker'), iter.get_node_at_current_location(), 10)
    iter.go_back_a_node()
    test(Node('Castor'), iter.get_node_at_current_location(), 10)
    iter.go_back_a_node()
    test(Node('Huntington'), iter.get_node_at_current_location(), 10)
    iter.go_back_a_node()
    test(Node('winterize'), iter.get_node_at_current_location(), 10)
    iter.go_back_a_node()
    test(Node('complainant'), iter.get_node_at_current_location(), 10)
    iter.go_back_a_node()
    test(Node('XS'), iter.get_node_at_current_location(), 10)
    iter.go_back_a_node()
    test(Node('foggy'), iter.get_node_at_current_location(), 10)
    try:
        iter.go_back_a_node()
        test('IndexError', 'no error occured', 10)
    except IndexError as err:
        test('IndexError', 'IndexError', 10)
    except AttributeError as err:
        test('IndexError', 'Attribute Error occured', 10)
    except ValueError as err:
        test('IndexError', 'ValueError', 10)
    list = LinkedList()
    list.add('aquaculture')
    iter = LinkedListIterator(list)
    test(Node('aquaculture'), iter.get_node_at_current_location(), 10)
    try:
        iter.go_back_a_node()
        test('IndexError', 'no error occured', 10)
    except IndexError as err:
        test('IndexError', 'IndexError', 10)
    except AttributeError as err:
        test('IndexError', 'Attribute Error occured', 10)
    except ValueError as err:
        test('IndexError', 'ValueError', 10)
    print('testing has_previous_node on a list with no nodes')
    already_printed_error = False
    list = LinkedList()
    iter = LinkedListIterator(list)
    try:
        test(False, iter.has_previous_node(), 5)
    except AttributeError as err:
        test('no error', 'Attribute Error occured ' + str(err), 5)
    except ValueError as err:
        test('no error', 'Value Error occured ' + str(err), 5)
    print('testing has_previous_node on a list with several nodes, for all nodes in list')
    already_printed_error = False
    list = LinkedList()
    list.add('directive')
    iter = LinkedListIterator(list)
    test(False, iter.has_previous_node(), 10)
    list = LinkedList()
    list.add('frontage')
    list.add('axolotl')
    list.add('parturition')
    list.add('backcomb')
    list.add('bibliographic')
    list.add('eucalypti')
    list.add('inaudible')
    list.add('rockiness')
    list.add('breastwork')
    iter = LinkedListIterator(list)
    test(False, iter.has_previous_node(), 10)
    iter.advance_to_next_node()
    test(True, iter.has_previous_node(), 10)
    iter.advance_to_next_node()
    test(True, iter.has_previous_node(), 10)
    iter.advance_to_next_node()
    test(True, iter.has_previous_node(), 10)
    iter.advance_to_next_node()
    test(True, iter.has_previous_node(), 10)
    iter.advance_to_next_node()
    test(True, iter.has_previous_node(), 10)
    iter.advance_to_next_node()
    test(True, iter.has_previous_node(), 10)
    iter.advance_to_next_node()
    test(True, iter.has_previous_node(), 10)
    iter.advance_to_next_node()
    test(True, iter.has_previous_node(), 10)
    list = LinkedList()
    list.add('Hallmark')
    list.add('contextualize')
    list.add('settlements')
    list.add('solace')
    list.add('schnozzle')
    iter = LinkedListIterator(list)
    test(False, iter.has_previous_node(), 10)
    iter.advance_to_next_node()
    test(True, iter.has_previous_node(), 10)
    iter.advance_to_next_node()
    test(True, iter.has_previous_node(), 10)
    iter.advance_to_next_node()
    test(True, iter.has_previous_node(), 10)
    iter.advance_to_next_node()
    test(True, iter.has_previous_node(), 10)
    list = LinkedList()
    list.add('pressure')
    list.add('functionalism')
    iter = LinkedListIterator(list)
    test(False, iter.has_previous_node(), 10)
    iter.advance_to_next_node()
    test(True, iter.has_previous_node(), 10)
    list = LinkedList()
    list.add('cochlear')
    list.add('trimmest')
    list.add('Acrux')
    list.add('wherefore')
    iter = LinkedListIterator(list)
    test(False, iter.has_previous_node(), 10)
    iter.advance_to_next_node()
    test(True, iter.has_previous_node(), 10)
    iter.advance_to_next_node()
    test(True, iter.has_previous_node(), 10)
    iter.advance_to_next_node()
    test(True, iter.has_previous_node(), 10)
    list = LinkedList()
    list.add('Hiss')
    list.add('governance')
    list.add('lxii')
    list.add('Julio')
    list.add('gland')
    list.add('somnolent')
    list.add('wheatgerm')
    list.add('deterioration')
    iter = LinkedListIterator(list)
    test(False, iter.has_previous_node(), 10)
    iter.advance_to_next_node()
    test(True, iter.has_previous_node(), 10)
    iter.advance_to_next_node()
    test(True, iter.has_previous_node(), 10)
    iter.advance_to_next_node()
    test(True, iter.has_previous_node(), 10)
    iter.advance_to_next_node()
    test(True, iter.has_previous_node(), 10)
    iter.advance_to_next_node()
    test(True, iter.has_previous_node(), 10)
    iter.advance_to_next_node()
    test(True, iter.has_previous_node(), 10)
    iter.advance_to_next_node()
    test(True, iter.has_previous_node(), 10)
    list = LinkedList()
    list.add('helpline')
    list.add('stink')
    list.add('Illinois')
    list.add('viewfinder')
    list.add('redivide')
    list.add('conjunctivitis')
    list.add('horehound')
    iter = LinkedListIterator(list)
    test(False, iter.has_previous_node(), 10)
    iter.advance_to_next_node()
    test(True, iter.has_previous_node(), 10)
    iter.advance_to_next_node()
    test(True, iter.has_previous_node(), 10)
    iter.advance_to_next_node()
    test(True, iter.has_previous_node(), 10)
    iter.advance_to_next_node()
    test(True, iter.has_previous_node(), 10)
    iter.advance_to_next_node()
    test(True, iter.has_previous_node(), 10)
    iter.advance_to_next_node()
    test(True, iter.has_previous_node(), 10)
    list = LinkedList()
    list.add('eradicable')
    list.add('cellphone')
    list.add('bellmen')
    iter = LinkedListIterator(list)
    test(False, iter.has_previous_node(), 10)
    iter.advance_to_next_node()
    test(True, iter.has_previous_node(), 10)
    iter.advance_to_next_node()
    test(True, iter.has_previous_node(), 10)
    list = LinkedList()
    list.add('sunflower')
    list.add('canker')
    list.add('nexus')
    list.add('orientalist')
    list.add('sectionalism')
    list.add('surliness')
    iter = LinkedListIterator(list)
    test(False, iter.has_previous_node(), 10)
    iter.advance_to_next_node()
    test(True, iter.has_previous_node(), 10)
    iter.advance_to_next_node()
    test(True, iter.has_previous_node(), 10)
    iter.advance_to_next_node()
    test(True, iter.has_previous_node(), 10)
    iter.advance_to_next_node()
    test(True, iter.has_previous_node(), 10)
    iter.advance_to_next_node()
    test(True, iter.has_previous_node(), 10)



test_suite()
print("points " + str(points))